apiVersion: v1
kind: Service
metadata:
  name: digital-wallet-service
  labels:
    app: digital-wallet-system
spec:
  selector:
    app: digital-wallet-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
